/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Mon Nov 28 15:56:33 2016. */

#include "lighthouse_sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t mkr1000_lighthouse_configObject_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, mkr1000_lighthouse_configObject, ip, ip, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, mkr1000_lighthouse_configObject, port, ip, 0),
    PB_LAST_FIELD
};

const pb_field_t mkr1000_lighthouse_trackedObjectConfig_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, mkr1000_lighthouse_trackedObjectConfig, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, mkr1000_lighthouse_trackedObjectConfig, ip, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, mkr1000_lighthouse_trackedObjectConfig, logging_port, ip, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, mkr1000_lighthouse_trackedObjectConfig, sensordata_port, logging_port, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, mkr1000_lighthouse_trackedObjectConfig, command_port, sensordata_port, 0),
    PB_LAST_FIELD
};

const pb_field_t mkr1000_lighthouse_loggingObject_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, mkr1000_lighthouse_loggingObject, message, message, 0),
    PB_LAST_FIELD
};

const pb_field_t mkr1000_lighthouse_commandObject_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, mkr1000_lighthouse_commandObject, command, command, 0),
    PB_LAST_FIELD
};

const pb_field_t mkr1000_lighthouse_sensor_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, mkr1000_lighthouse_sensor, id, id, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_sensor, lighthouse, id, 0),
    PB_FIELD(  3, INT32   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_sensor, timestamp, lighthouse, 0),
    PB_FIELD(  4, FLOAT   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_sensor, angles_h, timestamp, 0),
    PB_FIELD(  5, FLOAT   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_sensor, angles_v, angles_h, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
