/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Mon Nov 21 17:49:06 2016. */

#include "lighthouse_sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t mkr1000_lighthouse_configObject_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, mkr1000_lighthouse_configObject, ip, ip, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, mkr1000_lighthouse_configObject, port, ip, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, mkr1000_lighthouse_configObject, id, port, 0),
    PB_LAST_FIELD
};

const pb_field_t mkr1000_lighthouse_trackedObject_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, mkr1000_lighthouse_trackedObject, s, s, &mkr1000_lighthouse_trackedObject_Sensor_fields),
    PB_LAST_FIELD
};

const pb_field_t mkr1000_lighthouse_trackedObject_Sensor_fields[9] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, mkr1000_lighthouse_trackedObject_Sensor, id, id, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, timestamp, id, 0),
    PB_FIELD(  3, BOOL    , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, sensors0, timestamp, 0),
    PB_FIELD(  4, FLOAT   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, angles0_h, sensors0, 0),
    PB_FIELD(  5, FLOAT   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, angles0_v, angles0_h, 0),
    PB_FIELD(  6, BOOL    , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, sensors1, angles0_v, 0),
    PB_FIELD(  7, FLOAT   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, angles1_h, sensors1, 0),
    PB_FIELD(  8, FLOAT   , REPEATED, STATIC  , OTHER, mkr1000_lighthouse_trackedObject_Sensor, angles1_v, angles1_h, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(mkr1000_lighthouse_trackedObject, s[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_mkr1000_lighthouse_configObject_mkr1000_lighthouse_trackedObject_mkr1000_lighthouse_trackedObject_Sensor)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(mkr1000_lighthouse_trackedObject, s[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_mkr1000_lighthouse_configObject_mkr1000_lighthouse_trackedObject_mkr1000_lighthouse_trackedObject_Sensor)
#endif


/* @@protoc_insertion_point(eof) */
