/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8-dev at Tue Jan 24 17:31:43 2017. */

#ifndef PB_MKR1000_LIGHTHOUSE_LIGHTHOUSE_SENSOR_PB_H_INCLUDED
#define PB_MKR1000_LIGHTHOUSE_LIGHTHOUSE_SENSOR_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _mkr1000_lighthouse_commandObject {
    int32_t command;
/* @@protoc_insertion_point(struct:mkr1000_lighthouse_commandObject) */
} mkr1000_lighthouse_commandObject;

typedef struct _mkr1000_lighthouse_configObject {
    uint32_t ip;
    int32_t logging_port;
    int32_t sensor_port;
/* @@protoc_insertion_point(struct:mkr1000_lighthouse_configObject) */
} mkr1000_lighthouse_configObject;

typedef struct _mkr1000_lighthouse_loggingObject {
    char message[60];
/* @@protoc_insertion_point(struct:mkr1000_lighthouse_loggingObject) */
} mkr1000_lighthouse_loggingObject;

typedef struct _mkr1000_lighthouse_trackedObjectConfig {
    uint32_t ip;
    int32_t command_port;
/* @@protoc_insertion_point(struct:mkr1000_lighthouse_trackedObjectConfig) */
} mkr1000_lighthouse_trackedObjectConfig;

/* Default values for struct fields */

/* Initializer values for message structs */
#define mkr1000_lighthouse_configObject_init_default {0, 0, 0}
#define mkr1000_lighthouse_trackedObjectConfig_init_default {0, 0}
#define mkr1000_lighthouse_loggingObject_init_default {""}
#define mkr1000_lighthouse_commandObject_init_default {0}
#define mkr1000_lighthouse_configObject_init_zero {0, 0, 0}
#define mkr1000_lighthouse_trackedObjectConfig_init_zero {0, 0}
#define mkr1000_lighthouse_loggingObject_init_zero {""}
#define mkr1000_lighthouse_commandObject_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define mkr1000_lighthouse_commandObject_command_tag 1
#define mkr1000_lighthouse_configObject_ip_tag   1
#define mkr1000_lighthouse_configObject_logging_port_tag 2
#define mkr1000_lighthouse_configObject_sensor_port_tag 3
#define mkr1000_lighthouse_loggingObject_message_tag 1
#define mkr1000_lighthouse_trackedObjectConfig_ip_tag 1
#define mkr1000_lighthouse_trackedObjectConfig_command_port_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t mkr1000_lighthouse_configObject_fields[4];
extern const pb_field_t mkr1000_lighthouse_trackedObjectConfig_fields[3];
extern const pb_field_t mkr1000_lighthouse_loggingObject_fields[2];
extern const pb_field_t mkr1000_lighthouse_commandObject_fields[2];

/* Maximum encoded size of messages (where known) */
#define mkr1000_lighthouse_configObject_size     28
#define mkr1000_lighthouse_trackedObjectConfig_size 17
#define mkr1000_lighthouse_loggingObject_size    62
#define mkr1000_lighthouse_commandObject_size    11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LIGHTHOUSE_SENSOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
